export default {
  FETCH_MONSTERS_REQUESTED: 'FETCH_MONSTERS_REQUESTED',
  FETCH_MONSTER_REQUESTED: 'FETCH_MONSTER_REQUESTED',
  FETCH_MONSTERS_FAILED: 'FETCH_MONSTERS_FAILED',
  FETCH_MONSTER_SUCCEEDED: 'FETCH_MONSTER_SUCCEEDED',
};
